name: Trigger tests

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  trigger_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger tests repo
        uses: peter-evans/repository-dispatch@v1
        with:
          token: "${{ secrets.PAT_TOKEN_ALL }}"
          repository: adriangavanescu/wordpress-automation
          event-type: trigger-tests
